// Regiones (primer nivel administrativo) de los países que vienen de geoBoundaries, revisadas a mano.
// La fuente trae nombres en inglés ("Havana", "Bay Islands"), sin tildes ("Sao Paulo"), con errores
// ("La Roja" por La Rioja, "Rio de Jeneiro"), con prefijos ("Provincia de Coclé") y códigos ISO
// repetidos o ausentes (Ecuador y México repiten uno; El Salvador no trae ninguno). Por eso cada región
// se reconoce por su nombre en la fuente, normalizado, y se le da su código ISO 3166-2 y su nombre
// oficial (en castellano; en portugués los estados de Brasil).
//
// Formato: [nombre en la fuente normalizado, código ISO 3166-2, nombre oficial]. Una región puede
// tener más de una fila si las ediciones de la fuente la escriben distinto.

export const normalizarRegion = (nombre) =>
  String(nombre)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/^(provincia|departamento|departemento)( de)? /, '')
    .replace(/ \((departamento|departemento|municipio)\)$/, '')
    .replace(/ province$/, '')
    .trim();

const tabla = {
  AR: [
    ['salta', 'AR-A', 'Salta'],
    ['buenos aires', 'AR-B', 'Buenos Aires'],
    ['ciudad autonoma de buenos aires', 'AR-C', 'Ciudad Autónoma de Buenos Aires'],
    ['ciudad de buenos aires', 'AR-C', 'Ciudad Autónoma de Buenos Aires'],
    ['san luis', 'AR-D', 'San Luis'],
    ['entre rios', 'AR-E', 'Entre Ríos'],
    ['la roja', 'AR-F', 'La Rioja'],
    ['la rioja', 'AR-F', 'La Rioja'],
    ['santiago del estero', 'AR-G', 'Santiago del Estero'],
    ['chaco', 'AR-H', 'Chaco'],
    ['san juan', 'AR-J', 'San Juan'],
    ['catamarca', 'AR-K', 'Catamarca'],
    ['la pampa', 'AR-L', 'La Pampa'],
    ['mendoza', 'AR-M', 'Mendoza'],
    ['misiones', 'AR-N', 'Misiones'],
    ['formosa', 'AR-P', 'Formosa'],
    ['neuquen', 'AR-Q', 'Neuquén'],
    ['rio negro', 'AR-R', 'Río Negro'],
    ['santa fe', 'AR-S', 'Santa Fe'],
    ['tucuman', 'AR-T', 'Tucumán'],
    ['chubut', 'AR-U', 'Chubut'],
    ['tierra del fuego', 'AR-V', 'Tierra del Fuego'],
    ['corrientes', 'AR-W', 'Corrientes'],
    ['cordoba', 'AR-X', 'Córdoba'],
    ['jujuy', 'AR-Y', 'Jujuy'],
    ['santa cruz', 'AR-Z', 'Santa Cruz'],
  ],
  BO: [
    ['beni', 'BO-B', 'Beni'],
    ['cochabamba', 'BO-C', 'Cochabamba'],
    ['chuquisaca', 'BO-H', 'Chuquisaca'],
    ['la paz', 'BO-L', 'La Paz'],
    ['pando', 'BO-N', 'Pando'],
    ['oruro', 'BO-O', 'Oruro'],
    ['potosi', 'BO-P', 'Potosí'],
    ['santa cruz', 'BO-S', 'Santa Cruz'],
    ['tarija', 'BO-T', 'Tarija'],
  ],
  BR: [
    ['acre', 'BR-AC', 'Acre'],
    ['alagoas', 'BR-AL', 'Alagoas'],
    ['amazonas', 'BR-AM', 'Amazonas'],
    ['amapa', 'BR-AP', 'Amapá'],
    ['bahia', 'BR-BA', 'Bahia'],
    ['ceara', 'BR-CE', 'Ceará'],
    ['distrito federal', 'BR-DF', 'Distrito Federal'],
    ['espirito santo', 'BR-ES', 'Espírito Santo'],
    ['goias', 'BR-GO', 'Goiás'],
    ['maranhao', 'BR-MA', 'Maranhão'],
    ['minas gerais', 'BR-MG', 'Minas Gerais'],
    ['mato grosso do sul', 'BR-MS', 'Mato Grosso do Sul'],
    ['mato grosso', 'BR-MT', 'Mato Grosso'],
    ['para', 'BR-PA', 'Pará'],
    ['paraiba', 'BR-PB', 'Paraíba'],
    ['pernambuco', 'BR-PE', 'Pernambuco'],
    ['piaui', 'BR-PI', 'Piauí'],
    ['parana', 'BR-PR', 'Paraná'],
    ['rio de jeneiro', 'BR-RJ', 'Rio de Janeiro'],
    ['rio de janeiro', 'BR-RJ', 'Rio de Janeiro'],
    ['rio granda do norte', 'BR-RN', 'Rio Grande do Norte'],
    ['rio grande do norte', 'BR-RN', 'Rio Grande do Norte'],
    ['rondonia', 'BR-RO', 'Rondônia'],
    ['roraima', 'BR-RR', 'Roraima'],
    ['rio grande do sul', 'BR-RS', 'Rio Grande do Sul'],
    ['santa catarina', 'BR-SC', 'Santa Catarina'],
    ['sergipe', 'BR-SE', 'Sergipe'],
    ['sao paulo', 'BR-SP', 'São Paulo'],
    ['tocantins', 'BR-TO', 'Tocantins'],
  ],
  CO: [
    ['amazonas', 'CO-AMA', 'Amazonas'],
    ['antioquia', 'CO-ANT', 'Antioquia'],
    ['arauca', 'CO-ARA', 'Arauca'],
    ['atlantico', 'CO-ATL', 'Atlántico'],
    ['bolivar', 'CO-BOL', 'Bolívar'],
    ['boyaca', 'CO-BOY', 'Boyacá'],
    ['caldas', 'CO-CAL', 'Caldas'],
    ['caqueta', 'CO-CAQ', 'Caquetá'],
    ['casanare', 'CO-CAS', 'Casanare'],
    ['cauca', 'CO-CAU', 'Cauca'],
    ['cesar', 'CO-CES', 'Cesar'],
    ['choco', 'CO-CHO', 'Chocó'],
    ['cordoba', 'CO-COR', 'Córdoba'],
    ['cundinamarca', 'CO-CUN', 'Cundinamarca'],
    ['bogota capital district', 'CO-DC', 'Bogotá D. C.'],
    ['bogota, d.c.', 'CO-DC', 'Bogotá D. C.'],
    ['guainia', 'CO-GUA', 'Guainía'],
    ['guaviare', 'CO-GUV', 'Guaviare'],
    ['huila', 'CO-HUI', 'Huila'],
    ['la guajira', 'CO-LAG', 'La Guajira'],
    ['magdalena', 'CO-MAG', 'Magdalena'],
    ['meta', 'CO-MET', 'Meta'],
    ['narino', 'CO-NAR', 'Nariño'],
    ['norte de santander', 'CO-NSA', 'Norte de Santander'],
    ['putumayo', 'CO-PUT', 'Putumayo'],
    ['quindio', 'CO-QUI', 'Quindío'],
    ['risaralda', 'CO-RIS', 'Risaralda'],
    ['santander', 'CO-SAN', 'Santander'],
    ['archipielago de san andres, providencia y santa catalina', 'CO-SAP', 'San Andrés, Providencia y Santa Catalina'],
    ['sucre', 'CO-SUC', 'Sucre'],
    ['tolima', 'CO-TOL', 'Tolima'],
    ['valle del cauca', 'CO-VAC', 'Valle del Cauca'],
    ['vaupes', 'CO-VAU', 'Vaupés'],
    ['vichada', 'CO-VID', 'Vichada'],
  ],
  CR: [
    ['alajuela', 'CR-A', 'Alajuela'],
    ['cartago', 'CR-C', 'Cartago'],
    ['guanacaste', 'CR-G', 'Guanacaste'],
    ['heredia', 'CR-H', 'Heredia'],
    ['limon', 'CR-L', 'Limón'],
    ['puntarenas', 'CR-P', 'Puntarenas'],
    ['san jose', 'CR-SJ', 'San José'],
  ],
  CU: [
    ['pinar del rio', 'CU-01', 'Pinar del Río'],
    ['havana', 'CU-03', 'La Habana'],
    ['matanzas', 'CU-04', 'Matanzas'],
    ['villa clara', 'CU-05', 'Villa Clara'],
    ['cienfuegos', 'CU-06', 'Cienfuegos'],
    ['sancti spiritus', 'CU-07', 'Sancti Spíritus'],
    ['ciego de avila', 'CU-08', 'Ciego de Ávila'],
    ['camaguey', 'CU-09', 'Camagüey'],
    ['las tunas', 'CU-10', 'Las Tunas'],
    ['holguin', 'CU-11', 'Holguín'],
    ['granma', 'CU-12', 'Granma'],
    ['santiago de cuba', 'CU-13', 'Santiago de Cuba'],
    ['guantanamo', 'CU-14', 'Guantánamo'],
    ['artemisa', 'CU-15', 'Artemisa'],
    ['mayabeque', 'CU-16', 'Mayabeque'],
    ['isle of youth', 'CU-99', 'Isla de la Juventud'],
  ],
  DO: [
    ['distrito nacional', 'DO-01', 'Distrito Nacional'],
    ['azua', 'DO-02', 'Azua'],
    ['bahoruco', 'DO-03', 'Bahoruco'],
    ['barahona', 'DO-04', 'Barahona'],
    ['dajabon', 'DO-05', 'Dajabón'],
    ['duarte', 'DO-06', 'Duarte'],
    ['la estrelleta', 'DO-07', 'Elías Piña'],
    ['el seybo', 'DO-08', 'El Seibo'],
    ['espaillat', 'DO-09', 'Espaillat'],
    ['independencia', 'DO-10', 'Independencia'],
    ['la altagracia', 'DO-11', 'La Altagracia'],
    ['la romana', 'DO-12', 'La Romana'],
    ['la vega', 'DO-13', 'La Vega'],
    ['maria trinidad sanchez', 'DO-14', 'María Trinidad Sánchez'],
    ['monte cristi', 'DO-15', 'Montecristi'],
    ['pedernales', 'DO-16', 'Pedernales'],
    ['peravia', 'DO-17', 'Peravia'],
    ['puerto plata', 'DO-18', 'Puerto Plata'],
    ['hermanas', 'DO-19', 'Hermanas Mirabal'],
    ['samana', 'DO-20', 'Samaná'],
    ['san cristobal', 'DO-21', 'San Cristóbal'],
    ['san juan', 'DO-22', 'San Juan'],
    ['san pedro de macoris', 'DO-23', 'San Pedro de Macorís'],
    ['sanchez ramirez', 'DO-24', 'Sánchez Ramírez'],
    ['santiago', 'DO-25', 'Santiago'],
    ['santiago rodriguez', 'DO-26', 'Santiago Rodríguez'],
    ['valverde', 'DO-27', 'Valverde'],
    ['monsenor nouel', 'DO-28', 'Monseñor Nouel'],
    ['monte plata', 'DO-29', 'Monte Plata'],
    ['hato mayor', 'DO-30', 'Hato Mayor'],
    ['san jose de ocoa', 'DO-31', 'San José de Ocoa'],
    ['santo domingo', 'DO-32', 'Santo Domingo'],
  ],
  EC: [
    ['azuay', 'EC-A', 'Azuay'],
    ['bolivar', 'EC-B', 'Bolívar'],
    ['carchi', 'EC-C', 'Carchi'],
    ['orellana', 'EC-D', 'Orellana'],
    ['esmeraldas', 'EC-E', 'Esmeraldas'],
    ['canar', 'EC-F', 'Cañar'],
    ['guayas', 'EC-G', 'Guayas'],
    ['chimborazo', 'EC-H', 'Chimborazo'],
    ['imbabura', 'EC-I', 'Imbabura'],
    ['loja', 'EC-L', 'Loja'],
    ['manabi', 'EC-M', 'Manabí'],
    ['napo', 'EC-N', 'Napo'],
    ['el oro', 'EC-O', 'El Oro'],
    ['pichincha', 'EC-P', 'Pichincha'],
    ['los rios', 'EC-R', 'Los Ríos'],
    ['morona santiago', 'EC-S', 'Morona Santiago'],
    ['santo domingo de los tsachilas', 'EC-SD', 'Santo Domingo de los Tsáchilas'],
    ['santa elena', 'EC-SE', 'Santa Elena'],
    ['tungurahua', 'EC-T', 'Tungurahua'],
    ['sucumbios', 'EC-U', 'Sucumbíos'],
    ['galapagos', 'EC-W', 'Galápagos'],
    ['cotopaxi', 'EC-X', 'Cotopaxi'],
    ['pastaza', 'EC-Y', 'Pastaza'],
    ['zamora chinchipe', 'EC-Z', 'Zamora Chinchipe'],
    // Territorios sin límite resuelto entre provincias (El Piedrero, Las Golondrinas…): sin código ISO
    ['zona no delimitada', 'EC-ZND', 'Zonas no delimitadas'],
  ],
  SV: [
    ['ahuachapan', 'SV-AH', 'Ahuachapán'],
    ['cabanas', 'SV-CA', 'Cabañas'],
    ['chalatenango', 'SV-CH', 'Chalatenango'],
    ['cuscatlan', 'SV-CU', 'Cuscatlán'],
    ['la libertad', 'SV-LI', 'La Libertad'],
    ['la paz', 'SV-PA', 'La Paz'],
    ['la union', 'SV-UN', 'La Unión'],
    ['morazan', 'SV-MO', 'Morazán'],
    ['san miguel', 'SV-SM', 'San Miguel'],
    ['san salvador', 'SV-SS', 'San Salvador'],
    ['san vicente', 'SV-SV', 'San Vicente'],
    ['santa ana', 'SV-SA', 'Santa Ana'],
    ['sonsonate', 'SV-SO', 'Sonsonate'],
    ['usulutan', 'SV-US', 'Usulután'],
  ],
  GT: [
    ['alta verapaz', 'GT-AV', 'Alta Verapaz'],
    ['baja verapaz', 'GT-BV', 'Baja Verapaz'],
    ['chimaltenango', 'GT-CM', 'Chimaltenango'],
    ['chiquimula', 'GT-CQ', 'Chiquimula'],
    ['escuintla', 'GT-ES', 'Escuintla'],
    ['guatemala', 'GT-GU', 'Guatemala'],
    ['huehuetenango', 'GT-HU', 'Huehuetenango'],
    ['izabal', 'GT-IZ', 'Izabal'],
    ['jalapa', 'GT-JA', 'Jalapa'],
    ['jutiapa', 'GT-JU', 'Jutiapa'],
    ['peten', 'GT-PE', 'Petén'],
    ['el progreso', 'GT-PR', 'El Progreso'],
    ['quiche', 'GT-QC', 'Quiché'],
    ['quetzaltenango', 'GT-QZ', 'Quetzaltenango'],
    ['retalhuleu', 'GT-RE', 'Retalhuleu'],
    ['sacatepequez', 'GT-SA', 'Sacatepéquez'],
    ['san marcos', 'GT-SM', 'San Marcos'],
    ['solola', 'GT-SO', 'Sololá'],
    ['santa rosa', 'GT-SR', 'Santa Rosa'],
    ['suchitepequez', 'GT-SU', 'Suchitepéquez'],
    ['totonicapan', 'GT-TO', 'Totonicapán'],
    ['zacapa', 'GT-ZA', 'Zacapa'],
  ],
  HN: [
    ['atlantida', 'HN-AT', 'Atlántida'],
    ['choluteca', 'HN-CH', 'Choluteca'],
    ['colon', 'HN-CL', 'Colón'],
    ['comayagua', 'HN-CM', 'Comayagua'],
    ['copan', 'HN-CP', 'Copán'],
    ['cortes', 'HN-CR', 'Cortés'],
    ['el paraiso', 'HN-EP', 'El Paraíso'],
    ['francisco morazan', 'HN-FM', 'Francisco Morazán'],
    ['gracias a dios', 'HN-GD', 'Gracias a Dios'],
    ['bay islands', 'HN-IB', 'Islas de la Bahía'],
    ['intibuca', 'HN-IN', 'Intibucá'],
    ['lempira', 'HN-LE', 'Lempira'],
    ['la paz', 'HN-LP', 'La Paz'],
    ['ocotepeque', 'HN-OC', 'Ocotepeque'],
    ['olancho', 'HN-OL', 'Olancho'],
    ['santa barbara', 'HN-SB', 'Santa Bárbara'],
    ['valle', 'HN-VA', 'Valle'],
    ['yoro', 'HN-YO', 'Yoro'],
  ],
  MX: [
    ['aguascalientes', 'MX-AGU', 'Aguascalientes'],
    ['baja california', 'MX-BCN', 'Baja California'],
    ['baja california sur', 'MX-BCS', 'Baja California Sur'],
    ['campeche', 'MX-CAM', 'Campeche'],
    ['chihuahua', 'MX-CHH', 'Chihuahua'],
    ['chiapas', 'MX-CHP', 'Chiapas'],
    ['distrito federal', 'MX-CMX', 'Ciudad de México'],
    ['coahuila de zaragoza', 'MX-COA', 'Coahuila'],
    ['colima', 'MX-COL', 'Colima'],
    ['durango', 'MX-DUR', 'Durango'],
    ['guerrero', 'MX-GRO', 'Guerrero'],
    ['guanajuato', 'MX-GUA', 'Guanajuato'],
    ['hidalgo', 'MX-HID', 'Hidalgo'],
    ['jalisco', 'MX-JAL', 'Jalisco'],
    ['mexico', 'MX-MEX', 'Estado de México'],
    ['michoacan de ocampo', 'MX-MIC', 'Michoacán'],
    ['morelos', 'MX-MOR', 'Morelos'],
    ['nayarit', 'MX-NAY', 'Nayarit'],
    ['nuevo leon', 'MX-NLE', 'Nuevo León'],
    ['oaxaca', 'MX-OAX', 'Oaxaca'],
    ['puebla', 'MX-PUE', 'Puebla'],
    ['queretaro de arteaga', 'MX-QUE', 'Querétaro'],
    ['quintana roo', 'MX-ROO', 'Quintana Roo'],
    ['sinaloa', 'MX-SIN', 'Sinaloa'],
    ['san luis potosi', 'MX-SLP', 'San Luis Potosí'],
    ['sonora', 'MX-SON', 'Sonora'],
    ['tabasco', 'MX-TAB', 'Tabasco'],
    ['tamaulipas', 'MX-TAM', 'Tamaulipas'],
    ['tlaxcala', 'MX-TLA', 'Tlaxcala'],
    ['veracruz de ignacio de la llave', 'MX-VER', 'Veracruz'],
    ['yucatan', 'MX-YUC', 'Yucatán'],
    ['zacatecas', 'MX-ZAC', 'Zacatecas'],
  ],
  NI: [
    ['north carribean coast autonomous region', 'NI-AN', 'Costa Caribe Norte'],
    ['south atlantic autonomous region', 'NI-AS', 'Costa Caribe Sur'],
    ['boaco', 'NI-BO', 'Boaco'],
    ['carazo', 'NI-CA', 'Carazo'],
    ['chinandega', 'NI-CI', 'Chinandega'],
    ['chontales', 'NI-CO', 'Chontales'],
    ['esteli', 'NI-ES', 'Estelí'],
    ['granada', 'NI-GR', 'Granada'],
    ['jinotega', 'NI-JI', 'Jinotega'],
    ['leon', 'NI-LE', 'León'],
    ['madriz', 'NI-MD', 'Madriz'],
    ['managua', 'NI-MN', 'Managua'],
    ['masaya', 'NI-MS', 'Masaya'],
    ['matagalpa', 'NI-MT', 'Matagalpa'],
    ['nueva segovia', 'NI-NS', 'Nueva Segovia'],
    ['rivas', 'NI-RI', 'Rivas'],
    ['rio san juan', 'NI-SJ', 'Río San Juan'],
  ],
  PA: [
    ['bocas del toro', 'PA-1', 'Bocas del Toro'],
    ['cocle', 'PA-2', 'Coclé'],
    ['colon', 'PA-3', 'Colón'],
    ['chiriqui', 'PA-4', 'Chiriquí'],
    ['darien', 'PA-5', 'Darién'],
    ['herrera', 'PA-6', 'Herrera'],
    ['los santos', 'PA-7', 'Los Santos'],
    ['panama', 'PA-8', 'Panamá'],
    ['veraguas', 'PA-9', 'Veraguas'],
    ['panama oeste', 'PA-10', 'Panamá Oeste'],
    ['comarca embera-wounaan', 'PA-EM', 'Comarca Emberá-Wounaan'],
    ['comarca guna yala', 'PA-KY', 'Comarca Guna Yala'],
    ['comarca ngabe-bugle', 'PA-NB', 'Comarca Ngäbe-Buglé'],
  ],
  PY: [
    ['asuncion', 'PY-ASU', 'Asunción'],
    ['concepcion', 'PY-1', 'Concepción'],
    ['san pedro', 'PY-2', 'San Pedro'],
    ['cordillera', 'PY-3', 'Cordillera'],
    ['guaira', 'PY-4', 'Guairá'],
    ['caaguazu', 'PY-5', 'Caaguazú'],
    ['caazapa', 'PY-6', 'Caazapá'],
    ['itapua', 'PY-7', 'Itapúa'],
    ['misiones', 'PY-8', 'Misiones'],
    ['paraguari', 'PY-9', 'Paraguarí'],
    ['alto parana', 'PY-10', 'Alto Paraná'],
    ['central', 'PY-11', 'Central'],
    ['neembucu', 'PY-12', 'Ñeembucú'],
    ['amambay', 'PY-13', 'Amambay'],
    ['canindeyu', 'PY-14', 'Canindeyú'],
    ['presidente hayes', 'PY-15', 'Presidente Hayes'],
    ['alto paraguay', 'PY-16', 'Alto Paraguay'],
    ['boqueron', 'PY-19', 'Boquerón'],
  ],
  UY: [
    ['artigas', 'UY-AR', 'Artigas'],
    ['canelones', 'UY-CA', 'Canelones'],
    ['cerro largo', 'UY-CL', 'Cerro Largo'],
    ['colonia', 'UY-CO', 'Colonia'],
    ['durazno', 'UY-DU', 'Durazno'],
    ['florida', 'UY-FD', 'Florida'],
    ['flores', 'UY-FS', 'Flores'],
    ['lavalleja', 'UY-LA', 'Lavalleja'],
    ['maldonado', 'UY-MA', 'Maldonado'],
    ['montevideo', 'UY-MO', 'Montevideo'],
    ['paysandu', 'UY-PA', 'Paysandú'],
    ['rio negro', 'UY-RN', 'Río Negro'],
    ['rocha', 'UY-RO', 'Rocha'],
    ['rivera', 'UY-RV', 'Rivera'],
    ['salto', 'UY-SA', 'Salto'],
    ['san jose', 'UY-SJ', 'San José'],
    ['soriano', 'UY-SO', 'Soriano'],
    ['tacuarembo', 'UY-TA', 'Tacuarembó'],
    ['treinta y tres', 'UY-TT', 'Treinta y Tres'],
  ],
  VE: [
    ['distrito capital', 'VE-A', 'Distrito Capital'],
    ['anzoategui', 'VE-B', 'Anzoátegui'],
    ['apure', 'VE-C', 'Apure'],
    ['aragua', 'VE-D', 'Aragua'],
    ['barinas', 'VE-E', 'Barinas'],
    ['bolivar', 'VE-F', 'Bolívar'],
    ['carabobo', 'VE-G', 'Carabobo'],
    ['cojedes', 'VE-H', 'Cojedes'],
    ['falcon', 'VE-I', 'Falcón'],
    ['guarico', 'VE-J', 'Guárico'],
    ['lara', 'VE-K', 'Lara'],
    ['merida', 'VE-L', 'Mérida'],
    ['miranda', 'VE-M', 'Miranda'],
    ['monagas', 'VE-N', 'Monagas'],
    ['nueva esparta', 'VE-O', 'Nueva Esparta'],
    ['portuguesa', 'VE-P', 'Portuguesa'],
    ['sucre', 'VE-R', 'Sucre'],
    ['tachira', 'VE-S', 'Táchira'],
    ['trujillo', 'VE-T', 'Trujillo'],
    ['yaracuy', 'VE-U', 'Yaracuy'],
    ['zulia', 'VE-V', 'Zulia'],
    ['dependencias federales', 'VE-W', 'Dependencias Federales'],
    ['la guaira', 'VE-X', 'La Guaira'],
    ['delta amacuro', 'VE-Y', 'Delta Amacuro'],
    ['amazonas', 'VE-Z', 'Amazonas'],
  ],
};

/** Regiones de un país: por nombre normalizado de la fuente → { code, name } */
export const regionesDe = (pais) => new Map((tabla[pais] ?? []).map(([clave, code, name]) => [clave, { code, name }]));

/** Todas las regiones oficiales de un país (para revisar que no falte ninguna) */
export const regionesOficiales = (pais) => [
  ...new Map((tabla[pais] ?? []).map(([, code, name]) => [code, { code, name }])).values(),
];
